=== nicolalesi/GestioneDocumentale/dati/DTD_ViniXML.dtd
<!ELEMENT Vini (Vino+)> <!-- Radice -->
<!-- Contenitore Vino, con tag -->
<!ELEMENT Vino (Tipologia, Denominazione, Descrizione, ValoreMassimo?, ValoreMinimo?,MateriaPrima?, Luogo)>
<!-- "?"non in tutti ci sono-->
<!ATTLIST Vino nome CDATA #REQUIRED>

<!-- Singole voci contenitore vino -->
<!ELEMENT Tipologia (#PCDATA)>
<!ELEMENT Denominazione (#PCDATA)>
<!ELEMENT Descrizione (#PCDATA)>
<!ELEMENT ValoreMassimo (#PCDATA)>
<!ELEMENT ValoreMinimo (#PCDATA)>
<!ELEMENT MateriaPrima (#PCDATA)>

<!ELEMENT Luogo (Regione+)> <!-- In alcuni + di una regione-->
<!-- Regione, con tag -->
<!ELEMENT Regione (Provincia+)> 
<!ATTLIST Regione nome CDATA #REQUIRED>
<!-- Provincia, con tag -->
<!ELEMENT Provincia (Città*)> <!-- In alcuni non c'è città-->
<!ATTLIST Provincia nome CDATA #REQUIRED>
<!-- Città, con tag -->
<!ELEMENT Città EMPTY>
<!ATTLIST Città nome CDATA #REQUIRED>

=== nicolalesi/GestioneDocumentale/dati/viniTest.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE Vini SYSTEM "DTD_ViniXML.dtd">
<Vini>
  <Vino nome="Vino 'Valdinievole' Bianco Superiore">
    <Tipologia>vino 'Bianco Superiore'</Tipologia>
    <Denominazione>DOC vino 'Valdinievole'</Denominazione>
    <Descrizione>Vitigno 'Altre Varietà A Bacca Bianca': massimo (&lt;=) 30%, Vitigno 'Trebbiano Toscano': minimo (&gt;=) 70%</Descrizione>
    <ValoreMinimo>70%</ValoreMinimo>
    <ValoreMassimo>30%</ValoreMassimo>
    <Luogo>
      <Regione nome="Toscana">
        <Provincia nome="Provincia di Pistoia" />
        <Provincia nome="Provincia di Pistoia">
          <Città nome="Buggiano" />
          <Città nome="Chiesina Uzzanese" />
          <Città nome="Lamporecchio" />
          <Città nome="Larciano" />
          <Città nome="Marliana" />
          <Città nome="Massa e Cozzile" />
          <Città nome="Monsummano Terme" />
          <Città nome="Montecatini Terme" />
          <Città nome="Pescia" />
          <Città nome="Pieve a Nievole" />
          <Città nome="Ponte Buggianese" />
          <Città nome="Uzzano" />
        </Provincia>
      </Regione>
    </Luogo>
  </Vino>
  <Vino nome="Vino 'Valdinievole' Bianco">
    <Tipologia>vino 'Bianco'</Tipologia>
    <Denominazione>DOC vino 'Valdinievole'</Denominazione>
    <Descrizione>Vitigno 'Altre Varietà A Bacca Bianca': massimo (&lt;=) 30%, Vitigno 'Trebbiano Toscano': minimo (&gt;=) 70%</Descrizione>
    <ValoreMinimo>70%</ValoreMinimo>
    <ValoreMassimo>30%</ValoreMassimo>
    <MateriaPrima>Vitigno 'Altre Varietà A Bacca Bianca', Vitigno 'Trebbiano Toscano'</MateriaPrima>
    <Luogo>
      <Regione nome="Toscana">
        <Provincia nome="Provincia di Pistoia" />
        <Provincia nome="Provincia di Pistoia">
          <Città nome="Buggiano" />
          <Città nome="Chiesina Uzzanese" />
          <Città nome="Lamporecchio" />
          <Città nome="Larciano" />
          <Città nome="Marliana" />
          <Città nome="Massa e Cozzile" />
          <Città nome="Monsummano Terme" />
          <Città nome="Montecatini Terme" />
          <Città nome="Pescia" />
          <Città nome="Pieve a Nievole" />
          <Città nome="Ponte Buggianese" />
          <Città nome="Uzzano" />
        </Provincia>
      </Regione>
    </Luogo>
  </Vino>
</Vini>
